import { Teachers } from "./columns"

export const data: Teachers[] = [
  {
    name: "Anzar Ahmad",
    email: "anzar@gmail.com",
    image: "/Anzar pic.jpeg",
    status: "active",
    lessonPlanGenerated: 39,
    activityGenerated: 39,
    feedbackGenerated: 39,
    conceptSimplifierGenerated: 39,
  },
  {
    name: "Monu",
    email: "monu@gmail.com",
    status: "active",
    lessonPlanGenerated: 27,
    activityGenerated: 27,
    feedbackGenerated: 27,
    conceptSimplifierGenerated: 27,
  },
  {
    name: "Sonu",
    email: "sonu@gmail.com",
    status: "inactive",
    lessonPlanGenerated: 8,
    activityGenerated: 38,
    feedbackGenerated: 38,
    conceptSimplifierGenerated: 38,
  },
  {
    name: "Rahim",
    email: "rahim@gmail.com",
    image: "",
    status: "moderate",
    lessonPlanGenerated: 5,
    activityGenerated: 25,
    feedbackGenerated: 25,
    conceptSimplifierGenerated: 25,
  },
  {
    name: "Ram",
    email: "ram@gmail.com",
    status: "inactive",
    lessonPlanGenerated: 10,
    activityGenerated: 10,
    feedbackGenerated: 10,
    conceptSimplifierGenerated: 10,
  },
]
